print("welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
percent = int(input("How much tip would you like to give? 10,12, or 15?"))
people = int(input("How many people to split the bill?"))
print("Each person should pay: $" + str(round(bill * (1+percent/100)/people)))